const prefixDM = 'DANH-MUC/';
const prefixACL = 'ACL/';
const prefixHRM = 'HRM/';
const prefixPTN = 'PTN/';
const prefixKHCN = 'KHCN/';

export const UrlConstant = {
    API: {
        DM_NGOAI_NGU: prefixDM + 'NgoaiNgus',
        DM_TINH_THANH: prefixDM + 'TinhThanhs',
        DM_QUAN_HUYEN: prefixDM + 'QuanHuyens',
        DM_PHUONG_XA: prefixDM + 'PhuongXas',
        DM_QUOC_GIA: prefixDM + 'QuocGias',
        DM_TRINH_DO_NGOAI_NGU: prefixDM + 'TrinhDoNgoaiNgus',
        DM_DAN_TOC: prefixDM + 'DanTocs',
        DM_TON_GIAO: prefixDM + 'TonGiaos',
        DM_TRINH_DO_VAN_HOA: prefixDM + 'TrinhDoVanHoas',
        DM_TRINH_DO_NHA_NUOC: prefixDM + 'TrinhDoNhaNuocs',
        DM_TRINH_DO_VI_TINH: prefixDM + 'TrinhDoViTinhs',
        DM_TRINH_DO_CHINH_TRI: prefixDM + 'TrinhDoChinhTris',
        DM_QUAN_HE_GIA_DINH: prefixDM + 'QuanHeGiaDinhs',
        DM_DOI_TUONG_CHINH_SACH: prefixDM + 'DoiTuongChinhSachs',
        DM_DOI_TUONG_DANH_GIA: prefixDM + 'DoiTuongDanhGias',
        DM_DOI_TUONG_THUC_HIEN: prefixDM + 'DoiTuongThucHiens',
        DM_LOAI_HOP_DONG: prefixDM + 'LoaiHopDongs',
        DM_NHOM_HOP_DONG: prefixDM + 'NhomHopDongs',
        DM_KHOI_CO_QUAN: prefixDM + 'KhoiCoQuans',
        DM_CO_QUAN: prefixDM + 'CoQuans',
        DM_HOC_VI: prefixDM + 'HocVis',
        DM_KHEN_THUONG: prefixDM + 'KhenThuongs',
        DM_SO_QUYET_DINH: prefixDM + 'QuyetDinhs',
        DM_KET_QUA_DANH_GIA: prefixDM + 'XepLoaiKetQuaDanhGias',
        DM_KY_LUAT: prefixDM + 'KyLuats',
        DM_TINH_TRANG_HON_NHAN: prefixDM + 'TinhTrangHonNhans',
        DM_TINH_TRANG_SUC_KHOE: prefixDM + 'TinhTrangSucKhoes',
        DM_TRINH_DO_CHUYEN_MON: prefixDM + 'TrinhDoChuyenMons',
        DM_CHUC_VU: prefixDM + 'ChucVus',
        DM_HINH_THUC_TRA_LOI: prefixDM + 'HinhThucTraLois',
        DM_HINH_THUC_DAO_TAO: prefixDM + 'HinhThucDaoTaos',
        DM_DANH_HIEU: prefixDM + 'DanhHieus',
        DM_CO_QUAN_TRUC_THUOC: prefixDM + 'CoQuanTrucThuocs',
        DM_NHOM_VIEC_LAM: prefixDM + 'NhomViTriViecLams',
        DM_VI_TRI_VIEC_LAM: prefixDM + 'ViTriViecLams',
        DM_NHOM_MAU: prefixDM + 'NhomMaus',
        DM_NHOM_NGACH: prefixDM + 'NhomNgachs',
        DM_NGACH_CONG_CHUC: prefixDM + 'NgachCongChucs',
        DM_BAC_LUONG: prefixDM + 'BacLuongs',
        DM_CHUC_DANH_KHOA_HOC: prefixDM + 'ChucDanhKhoaHocs',
        DM_CHUC_DANH: prefixDM + 'ChucDanhs',
        DM_XEP_LOAI_KET_QUA_DANH_GIA: prefixDM + 'XepLoaiKetQuaDanhGias',
        DM_MUC_DO_HOAN_THANH: prefixDM + 'MucDoHoanThanhs',
        DM_TRANG_THAI_TIEN_DO: prefixDM + 'TrangThaiTienDos',
        DM_GIOI_TINH: prefixDM + 'GioiTinhs',
        DM_LOAI_NHAN_SU: prefixDM + 'LoaiNhanSus',
        DM_LOAI_NHAN_SU_DANH_GIA: prefixDM + 'LoaiNhanSuDanhGias',
        DM_LINH_VUC: prefixDM + 'LinhVucs',
        DM_TAP_CHI: prefixDM + 'TapChis',
        DM_HOI_NGHI: prefixDM + 'HoiNghis',
        DM_CAP_QUYET_DINH: prefixDM + 'CapQuyetDinhs',
        DM_CHUC_VU_DOAN: prefixDM + 'ChucVuDoans',
        DM_CHUC_VU_DANG: prefixDM + 'ChucVuDangs',
        DM_CHUC_VU_CONG_DOAN: prefixDM + 'ChucVuCongDoans',
        DM_CHUC_VU_CUU_CHIEN_BINH: prefixDM + 'ChucVuCuuChienBinhs',
        DM_LOAI_THUONG_BINH: prefixDM + 'LoaiThuongBinhs',
        DM_KY_NANG_NGOAI_NGU: prefixDM + 'KyNangNgoaiNgus',
        DM_QUAN_HAM: prefixDM + 'QuanHams',
        DM_NGUON_TUYEN_DUNG: prefixDM + 'NguonTuyenDungs',
        DM_TRANG_THAI_DUYET_KH: prefixDM + 'TrangThaiDuyetKeHoachs',
        DM_CHUYEN_NGANH: prefixDM + 'ChuyenNganhs',
        DM_NGANH: prefixDM + 'Nganhs',
        DM_KHOAN_PHU_CAP: prefixDM + 'KhoanPhuCaps',
        DM_VAN_BANG: prefixDM + 'VanBangs',
        DM_CHUNG_CHI: prefixDM + 'ChungChis',
        DM_THANH_PHAN_GIA_DINH: prefixDM + 'ThanhPhanGiaDinhs',

        DM_KE_HOACH_TUYEN_DUNG: prefixHRM + 'KeHoachTuyenDungs',

        // SURVEY
        PKS_DANH_GIA: prefixHRM + 'DanhGias',
        PKS_DOT_DANH_GIA: prefixHRM + 'DotDanhGias',
        PKS_PHIEU_DANH_GIA: prefixHRM + 'PhieuDanhGias',
        PKS_PHAN_LOAI_DANH_GIA: prefixHRM + 'PhanLoaiDanhGias',
        PKS_TONG_HOP_KET_QUA_DANH_GIA: prefixHRM + 'TongHopKetQuaDanhGias',
        PKS_NHAN_SU_DANH_GIA_CHI_TIET: prefixHRM + 'NhanSuDanhGiaChiTiets',
        PKS_TONG_HOP_KET_QUA: prefixHRM + 'TongHopKetQuas',
        PKS_TONG_HOP_PHIEU_DANH_GIA: prefixHRM + 'TongHopPhieuDanhGias',
        PKS_THONG_KE_THEO_CAP_DON_VI: prefixHRM + 'ThongKeTheoCapDonVis',

        // HUMAN RESOURCE
        HRM_NHAN_SU: prefixHRM + 'NhanSus',
        HRM_NHAN_SU_CHI_TIET: prefixHRM + 'NhanSuChiTiets',
        HRM_DANH_MUC_CO_QUAN: prefixHRM + 'DanhMucCoQuans',
        HRM_NS_THONG_TIN_TUYEN_DUNG: prefixHRM + 'NhanSuTuyenDungs',
        HRM_NS_LUONG: prefixHRM + 'NhanSuLuongs',
        HRM_NS_QUAN_HE_GIA_DINH: prefixHRM + 'NhanSuQuanHeGiaDinhs',
        HRM_NS_LICH_SU_CA_NHAN: prefixHRM + 'NhanSuLichSuCaNhans',
        HRM_NS_HOAN_CANH_KINH_TE: prefixHRM + 'NhanSuHoanCanhKinhTes',
        HRM_NS_DOAN_DANG: prefixHRM + 'NhanSuDoanDangs',
        HRM_NS_QUA_TRINH_CONG_DOAN: prefixHRM + 'NhanSuQuaTrinhCongDoans',
        HRM_NS_QUA_TRINH_DANG: prefixHRM + 'NhanSuQuaTrinhDangs',
        HRM_NS_QUA_TRINH_DOAN: prefixHRM + 'NhanSuQuaTrinhDoans',
        HRM_NS_TRINH_DO_NGOAI_NGU: prefixHRM + 'NhanSuTrinhDoNgoaiNgus',
        HRM_NS_TRINH_DO_TIN_HOC: prefixHRM + 'NhanSuTrinhDoTinHocs',
        HRM_NS_TRINH_DO: prefixHRM + 'NhanSuTrinhDos',
        HRM_NS_TRINH_DO_CHUYEN_MON: prefixHRM + 'NhanSuTrinhDoChuyenMons',
        HRM_NS_CHUC_DANH_KHOA_HOC: prefixHRM + 'NhanSuChucDanhKhoaHocs',
        HRM_NS_QUA_TRINH_CONG_TAC: prefixHRM + 'NhanSuQuaTrinhCongTacs',
        HRM_NS_DAO_TAO_BOI_DUONG: prefixHRM + 'NhanSuDaoTaoBoiDuongs',
        HRM_NS_KHEN_THUONG: prefixHRM + 'NhanSuKhenThuongs',
        HRM_NS_KY_LUAT: prefixHRM + 'NhanSuKyLuats',
        HRM_NS_SUC_KHOE: prefixHRM + 'NhanSuSucKhoes',
        HRM_NS_KIEM_NHIEM: prefixHRM + 'NhanSuKiemNhiems',
        HRM_NS_DANH_HIEU_THI_DUA_KHEN_THUONG: prefixHRM + 'NhanSuThiDuaKhenThuongs',
        HRM_NS_REPORT: prefixHRM + 'NhanSuReports',
        HRM_NS_DUYET_HO_SO_TRUNG_TUYEN: prefixHRM + 'NhanSuDuyetHoSoUngVienTrungTuyens',
        HRM_NS_THONG_TIN_TAB_DE_XUAT: prefixHRM + 'NhanSuThongTinTabDeXuats',

        HRM_DM_TIEU_CHUAN_TUYEN_DUNG: prefixHRM + 'TieuChuanTuyenDungs',
        HRM_TD_KE_HOACH_TIEU_CHUAN: prefixHRM + 'KeHoachTuyenDungTieuChuans',
        HRM_TD_KE_HOACH_TUYEN_DUNG: prefixHRM + 'KeHoachTuyenDungs',
        HRM_TD_QUYET_DINH: prefixHRM + 'QuyetDinhs',
        HRM_TD_KE_HOACH_TUYEN_DUNG_CHI_TIET: prefixHRM + 'KeHoachTuyenDungChiTiets',
        HRM_TD_KE_HOACH_DE_XUAT: prefixHRM + 'KeHoachTuyenDungDeXuats',

        HRM_SETTING_BIEU_MAU: prefixHRM + 'SysBieuMaus',

        HRM_MEDIA: prefixHRM + 'Medias/UploadFile',

        // Ly Lich Khoa Hoc
        LLKH_BANG_SO_HUU_TRI_TUE: prefixHRM + 'LyLichKhoaHocBangSoHuuTriTues',
        LLKH_CONG_TRINH_KHOA_HOC: prefixHRM + 'LyLichKhoaHocCongTrinhKhoaHocs',
        LLKH_SACH_GIAO_TRINH: prefixHRM + 'LyLichKhoaHocVietSachs',
        LLKH_SAN_PHAM_UNG_DUNG: prefixHRM + 'LyLichKhoaHocSanPhams',
        LLKH_GIAI_THUONG_KHCN: prefixHRM + 'LyLichKhoaHocGiaiThuongs',
        LLKH_THAM_GIA_DAO_TAO_SDH: prefixHRM + 'LyLichKhoaHocQuaTrinhThamGiaDaoTaos',
        LLKH_DE_TAI_KHCN: prefixHRM + 'LyLichKhoaHocDeTaiKHCNs',
        LLKH_REPORT: prefixHRM + 'LyLichKhoaHocReports',

        // Tuyen dung
        TD_DINH_BIEN: prefixHRM + 'DinhBiens',
        TD_QUYET_DINH: prefixHRM + 'QuyetDinhs',
        TD_QUYET_DINH_REPORTS: prefixHRM + 'QuyetDinhReports',
        TD_HOP_DONG: prefixHRM + 'HopDongs',
        TD_HOP_DONG_PHU_CAP: prefixHRM + 'HopDongChiTietPhuCaps',
        TD_QUA_TRINH_TAP_SU: prefixHRM + 'QuaTrinhTapSus',
        TD_THONG_KE_TUYEN_DUNG: prefixHRM + 'ThongKeTuyenDungNhanSus',
        TD_KE_HOACH_LICH_SU: prefixHRM + 'KeHoachTuyenDungLichSus',
        TD_REPORT: prefixHRM + 'TuyenDungReports',

        // PERMISSION
        ACL_ACCOUNT: prefixACL + 'Accounts',
        ACL_PERMISSION: prefixACL + 'Permissions',
        ACL_USER: prefixACL + 'Users',
        ACL_USER_DEVICE_DETAIL: prefixACL + 'UserDeviceDetails',
        ACL_PERMISSION_GROUP_USER: prefixACL + 'PermissionGroupUsers',
        ACL_PERMISSION_GROUP: prefixACL + 'PermissionGroups',
        ACL_PERMISSION_GROUP_ACTION: prefixACL + 'PermissionGroupActions',
        ACL_GROUP_CREATION_PERMISSION: prefixACL + 'GroupCreationPermissions',

        /* Phòng thí nghiệm */
        DM_CAP_DO: prefixPTN + 'DM_CapDos',
        DM_CAP_QUAN_LY: prefixPTN + 'DM_CapQuanLys',
        DM_NGANH_DAO_TAO: prefixDM + 'Nganhs',
        DM_CHUYEN_NGANH_DAO_TAO: prefixDM + 'ChuyenNganhs',
        DM_NHOM_CONG_CU: prefixPTN + 'DM_NhomCongCus',
        DM_CONG_CU: prefixPTN + 'DM_CongCus',
        DM_TINH_TRANG_THIET_BI: prefixPTN + 'DM_TinhTrangThietBis',
        DM_LOAI_PHONG_TN: prefixPTN + 'DM_LoaiHinhPhongs',
        DM_KY_NANG_VAN_HANH: prefixPTN + 'DM_KyNangVanHanhs',
        DM_LOAI_HINH_PHONG: prefixPTN + 'DM_LoaiHinhPhongs',
        DM_TRANG_THAI_DANG_KY_PHONG: prefixPTN + 'DM_TrangThaiDangKyPhongs',
        DM_VAI_TRO: prefixPTN + 'DM_VaiTros',
        PTN_READPHONGTHINGHIEM: prefixPTN + 'ReadPhongThiNghiems',
        PTN_PHONGTHINGHIEM: prefixPTN + 'PhongThiNghiems',
        PTN_THIETBI: prefixPTN + 'TB_ThietBis',
        PTN_VAT_TU_TIEU_HAO: prefixPTN + 'TB_VatTuTieuHaos',
        PTN_DANG_KY_SD_PTN: prefixPTN + 'DangKySuDungs',
        DM_TRANG_THAI_DANG_KY_PTN: prefixPTN + 'DM_TrangThaiDangKyPhongs',
        NHAT_KY_SU_DUNG_PHONG: prefixPTN + 'DangKySuDung_NhatKySuDungs',
        DM_DON_VI_TINH: prefixPTN + 'DM_DonViTinhs',
        THIET_BI_PHU_THUOC: prefixPTN + 'TB_ThietBiPhuThuocs',
        HUONG_DAN_SU_DUNG: prefixPTN + 'TB_HuongDanSuDungs',
        BAO_HANH_BAO_TRI: prefixPTN + 'TB_BaoHanhBaoTris',
        MANG_RA_NGOAI: prefixPTN + 'TB_MangRaNgoais',
        DOI_NGU_CAN_BO: prefixPTN + 'DoiNguCanBos',
        DM_VAI_TRO_DNCB: prefixPTN + 'DM_VaiTros',
        SAN_PHAM_KHCN: prefixPTN + 'SanPhamKHCNs',
        PHAN_QUYEN_PHU_TRACH: prefixPTN + 'PhanQuyenPhuTrachPhongs',
        NHOM_NGHIEN_CUU: prefixPTN + 'NhomNghienCuus',
        HOP_DONG_KHAI_THAC: prefixPTN + 'HopDongKhaiThacs',
        THU_HUT_NHA_KHOA_HOC: prefixPTN + 'ThuHutNhaKhoaHocs',
        DANG_KY_SO_HUU_TRI_TUE: prefixPTN + 'DangKySoHuuTriTues',




        /* Khoa học công nghệ */
        NHIEM_VU_KHCN: prefixKHCN + 'NhiemVuKhoaHocs',
        KHCN_SACH_CHUYEN_KHAO: prefixKHCN + 'SachChuyenKhaos',
        KHCN_BAO_CAO_KHOA_HOC: prefixKHCN + 'BaoCaoKhoaHocs',
        DM_LOAI_HOI_THAO_HOI_NGHI: prefixKHCN + 'DM_LoaiHoiThaoHoiNghis',
        DM_LOAI_BAO_CAO: prefixKHCN + 'DM_LoaiBaoCaos',
        DM_LOAI_HOI_NGHI_HOI_THAO: prefixKHCN + 'DM_LoaiHoiThaoHoiNghis',
        DM_NHOM_KET_QUA_DU_KIEN: prefixKHCN + 'DM_NhomKetQuaDuKiens',
        KHCN_SAN_PHAM_DA0_TAO: prefixKHCN + 'SanPhamDaoTaos',
        KHCN_PHAT_MINH_SANG_CHE: prefixKHCN + 'PhatMinhSangChes',
        DM_TINH_TRANG_DANG_KY: prefixKHCN + 'DM_TinhTrangDangKys',
        DM_HINH_THUC: prefixKHCN + 'DM_HinhThucs',
        DM_TINH_TRANG_SAN_PHAM: prefixKHCN + 'DM_TinhTrangSanPhams',
        BAI_BAO_KHCN: prefixKHCN + 'BaiBaoKhoaHocs',
        GIAI_THUONG_KHCN: prefixKHCN + 'GiaiThuongKHCNs',
        DM_LOAI_GIAI_THUONG: prefixKHCN + 'DM_LoaiGiaiThuongs',
        DM_THU_HANG_GIAI_THUONG: prefixKHCN + 'DM_ThuHangGiaiThuongs',
        KHCN_HOI_NGHI_HOI_THAO: prefixKHCN + 'HoiThaoHoiNghis',
        KHCN_DU_AN_DAU_TU: prefixKHCN + 'DuAnDauTus',
        DM_LOAI_DU_AN: prefixKHCN + 'DM_LoaiDuAns',
        DM_KET_QUA_DU_KIEN: prefixKHCN + 'DM_KetQuaDuKiens',
        DM_THANH_VIEN_NGOAI: prefixKHCN + 'DM_ThanhVienNgoais',
        DM_TO_CHUC_CAP_BANG: prefixKHCN + 'DM_ToChucCapBangs',
        DM_TRANG_THAI_KHCN: prefixKHCN + 'DM_TrangThaiKHCNs',
        DM_VAI_TRO_KHCN: prefixKHCN + 'DM_VaiTros',
        DM_TAP_CHI_KHCN: prefixKHCN + 'DM_TapChis',
        DM_CAP_DO_KHCN: prefixKHCN + 'DM_CapDos',
        DM_LOAI_KE_HOACH: prefixKHCN + 'KH_DM_LoaiKeHoachs',









        /*Lập kế hoạch Khoa học công nghệ */
        LKH_KHCN_LAP_KE_HOACH_THONG_BAO: prefixKHCN + 'KH_ThongBaos',
        LKH_KHCN_PHAN_CONG_THUC_HIEN: prefixKHCN + 'KH_PhanCongThucHiens',
        

        // SYSTEM
        SYSTEM: {
            MAN_HINH: prefixACL + 'Functions',
            CHUC_NANG: prefixACL + 'Actions',
            USERS: prefixACL + 'Users',
        },
    },
    ROUTE: {
        LOGIN: '/login',
        DASHBOARD: '/management/dashboard',
        FORBIDEN: '/management/403',
        PROFILE: '/management/profile',
        LOGIN_NS: '/management/login-ns',

        PKS_DANH_GIA: '/management/survey/danh-gia',
        PKS_LIST_PHIEU_TU_DANH_GIA: '/management/survey/tu-danh-gia',
        PKS_PHIEU_TU_DANH_GIA: '/management/survey/phieu-tu-danh-gia',
        PKS_LIST_QUAN_LY_DANH_GIA: '/management/survey/quan-ly-danh-gia',
        PKS_PHIEU_QUAN_LY_DANH_GIA: '/management/survey/phieu-quan-ly-danh-gia',
        PKS_LIST_BAN_QUAN_LY_DANH_GIA: '/management/survey/ban-quan-ly-danh-gia',
        PKS_PHIEU_BAN_QUAN_LY_DANH_GIA: '/management/survey/phieu-ban-quan-ly-danh-gia',

        HRM_THONG_TIN_NHAN_SU: '/management/human-resource/ho-so-ca-nhan/thong-tin-nhan-su',
        HRM_DUYET_HO_SO_NHAN_SU: '/management/human-resource/ho-so-ung-vien/thong-tin-nhan-su',
        HRM_DUYET_LY_LICH_NHAN_SU: '/management/human-resource/duyet-ho-so-ca-nhan/thong-tin-nhan-su',
        HRM_LY_LICH_NHAN_SU: '/management/human-resource/ly-lich-nhan-su/thong-tin-nhan-su',

        TD_QUYET_DINH_TUYEN_DUNG: 'management/tuyen-dung/quyet-dinh-tuyen-dung',
        CATALOG: {
            NGOAI_NGU: '/admin/index/ngoai-ngu',
        },
    },
};
