export interface IQuyetDinhPhanCongHuongDanTapSu {
    id: number;
    idQuyetDinh: number;
    idNhanSuTapSu: number;
    idPhanCongHuongDanTapSu: number;
    userName: string,
    hoDem: string,
    ten: string,
    tenGioiTinh: string,
    ngaySinh: Date;
    tenCoQuan: string,
    tenViTriViecLam: string,
    tenNhanSuNhanQuyetDinh: string,
    tapSuTuNgay: Date;
    tapSuDenNgay: Date;
    nopBaoCaoTuNgay: Date;
    nopBaoCaoDenNgay: Date;
    soQuyetDinh: string,
    tenNguoiXetDuyet: string,
    ngayKy: Date,
    tenChucVuNguoiQuyetDinh: string
    ngayQuyetDinh: Date;
    ngayHieuLuc: Date;
    heSoTrachNhiem: number;
    ghiChu: string;
    idNhanSuNhanQuyetDinh: number;
    idNguoiKy: number;
    checkSumFileDinhKem: string;
    forWebFileDinhKem: string;
    guidIdFileDinhKem: string;
    idFileDinhKem: number;
    idNguoiXetDuyet: number;
    idViTriViecLam: number;
    nameFileDinhKem: string;
    pathFileDinhKem: string;
    sizeFileDinhKem: number;
    tenNhanSuTapSu: string;
    typeFileDinhKem: string;
    idCoQuanCap1: number;
}
export interface IPhanCongBaoCaoTapSu {
    id: number;
    congViecDuocPhanCong: string,
    phamChatDaoDuc: string,
    nangLuc: string,
    yThucToChuc: string,
    thamGiaCongTac: string,
    nhanXet: string,
    deXuatKhac: string,
    trangThai: number;
    ghiChu: string,
    idPhanCongHuongDanTapSu: number;
    ngayNopBaoCao: Date;
    ngayDanhGia: Date;
    idFileDinhKem: number;
    nameFileDinhKem: string,
    typeFileDinhKem: number;
    sizeFileDinhKem: number;
    pathFileDinhKem: string,
    forWebFileDinhKem: true,
    checkSumFileDinhKem: string,
    idNhanSuTapSu: number;
    hoTenTapSu: string,
    idViTriViecLam: number;
    tenViTriViecLam: string,
    tapSuDenNgay: Date;
}
